// ==========================================================================
// Extensions supporting EMProcedure, EMDiagnosticReport, EMAllergyIntolerance,
// EMCondition, EMSecondarySurveyObservation, EMVitalSignsObservation,
// EMMedicationAdministration, and EMResponderUnit.
// ==========================================================================


// --------------------------------------------------------------------------
// Responder Unit (Device) extensions
// --------------------------------------------------------------------------

Extension: EMOwnershipType
Id: em-ownership-type
Title: "Emergency Responder Unit Ownership Type"
Description: """
Ownership category of the organization operating an emergency responder unit,
e.g. government, private, or NGO.
"""
Context: Device

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept 1..1 MS
* valueCodeableConcept from EMOwnershipTypeVS (required)
* valueCodeableConcept ^short = "Ownership category of the operating organization"


Extension: EMTelematicsDeviceId
Id: em-telematics-device-id
Title: "Emergency Responder Unit Telematics Device Identifier"
Description: """
Identifier of the onboard telematics or tracking device fitted to an emergency
responder unit, if present.
"""
Context: Device

* extension 0..0
* value[x] only string
* valueString 1..1 MS
* valueString ^short = "Onboard telematics/tracking device identifier"


Extension: EMRelieved
Id: em-relieved
Title: "Emergency Responder Unit Relieved Status"
Description: """
Indicates whether a responder unit has been stood down or replaced by another
unit during the incident.
"""
Context: Device

* extension 0..0
* value[x] only boolean
* valueBoolean 1..1 MS
* valueBoolean ^short =
    "Whether the unit has been stood down or replaced during the incident"
* valueBoolean ^definition = """
A value of true indicates that this unit has been relieved or reassigned and
is no longer the actively responding unit for the incident. Matters for
mass-casualty-incident reporting, where a stood-down unit could otherwise be
mistaken for one still actively responding.
"""


// --------------------------------------------------------------------------
// Responder Unit real-time position (Location) extensions
// --------------------------------------------------------------------------

Extension: EMLastLocationUpdatedAt
Id: em-last-location-updated-at
Title: "Emergency Responder Unit Last Location Updated At"
Description: """
Date and time the responder unit's geographic position was last refreshed.
"""
Context: Location

* extension 0..0
* value[x] only dateTime
* valueDateTime 1..1 MS
* valueDateTime ^short = "When the position was last refreshed"
* valueDateTime ^definition = """
Critical for knowing whether a displayed position is current or stale. A
dispatch dashboard should visibly flag units whose last-updated timestamp is
old.
"""


Extension: EMUnitResponseStatus
Id: em-unit-response-status
Title: "Emergency Responder Unit Response Status"
Description: """
The responder unit's current response state, e.g. dispatched, en-route,
on-scene, transporting, or at-facility.
"""
Context: Location

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept 1..1 MS
* valueCodeableConcept from EMUnitResponseStatusVS (required)
* valueCodeableConcept ^short = "Current response state of the unit"


// --------------------------------------------------------------------------
// Vital signs (Observation) extensions
// --------------------------------------------------------------------------

Extension: EMClinicalGuidanceMessage
Id: em-clinical-guidance-message
Title: "Emergency Clinical Guidance Message"
Description: """
Auto-generated clinical guidance text tied to an observation's severity flag,
e.g. instructions to start supplemental oxygen and reassess airway and
breathing.
"""
Context: Observation

* extension 0..0
* value[x] only string
* valueString 1..1 MS
* valueString ^short = "Clinical decision-support guidance text"
* valueString ^definition = """
Clinical decision-support content generated by the source system alongside a
coded interpretation flag. Preserve verbatim rather than discarding once the
coded interpretation is captured, since the specific wording may carry
protocol-specific instructions.
"""


Extension: EMQualitativeState
Id: em-qualitative-state
Title: "Emergency Vital Sign Qualitative State"
Description: """
Qualitative descriptor of a vital-sign reading, independent of its numeric
value, e.g. a pulse described as weak or a breathing pattern described as
labored.
"""
Context: Observation

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept 1..1 MS
* valueCodeableConcept from EMVitalQualitativeStateVS (required)
* valueCodeableConcept ^short = "Qualitative descriptor independent of the numeric value"


Extension: EMVitalAgeGroup
Id: em-vital-age-group
Title: "Emergency Vital Sign Age Group"
Description: """
Age-group bucket used to select the applicable reference range for a vital-sign
reading, e.g. adult versus paediatric.
"""
Context: Observation

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept 1..1 MS
* valueCodeableConcept from EMAgeGroupVS (required)
* valueCodeableConcept ^short = "Age-group bucket used to select the reference range"
* valueCodeableConcept ^definition = """
Ties directly to the EMIsAdult extension on the Patient resource; keep the two
consistent for a given patient rather than letting them drift independently
across resources.
"""


// --------------------------------------------------------------------------
// Physical exam (Observation) extension
// --------------------------------------------------------------------------

Extension: EMNoFindingsOnExam
Id: em-no-findings-on-exam
Title: "Emergency No Findings On Exam"
Description: """
Explicit flag confirming that a body region was examined and that nothing
abnormal was found.
"""
Context: Observation

* extension 0..0
* value[x] only boolean
* valueBoolean 1..1 MS
* valueBoolean ^short = "Whether the region was examined with no abnormal findings"
* valueBoolean ^definition = """
Must always be populated: true when no finding is coded on this Observation,
false whenever any finding is coded. A region-examination record must never
leave both findings and this flag absent, since that combination is exactly
the ambiguity ("was this region even checked?") this extension exists to
eliminate.
"""


// --------------------------------------------------------------------------
// Medication administration extension
// --------------------------------------------------------------------------

Extension: EMAdministrationAttempts
Id: em-administration-attempts
Title: "Emergency Medication Administration Attempts"
Description: """
Number of attempts made to administer a medication, relevant for
repeated-dose protocols and difficult-access scenarios.
"""
Context: MedicationAdministration

* extension 0..0
* value[x] only positiveInt
* valuePositiveInt 1..1 MS
* valuePositiveInt ^short = "Number of administration attempts made"
* valuePositiveInt ^definition = """
Counts administration attempts (e.g. repeated IV attempts before a drug was
successfully given), distinct from the number of doses given.
"""
